name: Deploy to S3 and CloudFront

on:
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Node version
      run: node -v

    - name: Installing Dependencies
      run: npm i

    - name: Linting
      run: npm run lint

    - name: Code coverage
      run: npm run test:ci

    - name: Build
      run: npm run build
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: dist/rohit-profile/


  deploy:
    name: Deployment to S3 and CloudFront
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: dist/rohit-profile/

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Cloudfront Invalidation and S#
      run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
          aws s3 cp dist/rohit-profile s3://${{ secrets.S3_BUCKET }}
